apiVersion: v1
kind: Secret
metadata:
  name: {{ include "litellm-gateway.fullname" . }}-secret
type: Opaque
stringData:
  LITELLM_MASTER_KEY: {{ .Values.admin.masterKey | quote }}
  OPENAI_COMPATIBLE_API_KEY: {{ .Values.backend.apiKey | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.password | quote }}
  DATABASE_URL: {{ printf "postgresql://%s:%s@%s-postgresql:5432/%s" .Values.postgresql.username .Values.postgresql.password (include "litellm-gateway.fullname" .) .Values.postgresql.database | quote }}
  GENERIC_CLIENT_SECRET: {{ .Values.sso.clientSecret | quote }}
