apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keycloak-ldaps-sso.fullname" . }}-secret
type: Opaque
stringData:
  KEYCLOAK_ADMIN: {{ .Values.keycloak.adminUser | quote }}
  KEYCLOAK_ADMIN_PASSWORD: {{ .Values.keycloak.adminPassword | quote }}
  LDAP_BIND_PASSWORD: {{ .Values.ldap.bindPassword | quote }}
  LITELLM_OIDC_CLIENT_SECRET: {{ .Values.oidcClient.clientSecret | quote }}
